# Aprende NumPy - Guía para Principiantes

Este cuaderno proporciona ejemplos para ayudarte a comenzar con **NumPy**, el paquete fundamental para la computación científica con Python. NumPy ofrece soporte para arreglos (arrays), matrices y muchas funciones matemáticas para operar con estos arreglos.

## Tabla de Contenidos:
1. [Introducción a NumPy](#introduccion)
2. [Creación de Arreglos](#creacion-arreglos)
3. [Operaciones con Arreglos](#operaciones-arreglos)
4. [Indexación y Slicing](#indexacion-slicing)
5. [Funciones Matemáticas](#funciones-matematicas)
6. [Broadcasting](#broadcasting)
7. [Cambio de Forma en Arreglos](#cambio-forma)


In [1]:

import numpy as np

# Introducción a NumPy
# NumPy es una biblioteca para trabajar con datos numéricos. Introduce el concepto de arreglos,
# que son estructuras de datos similares a listas, pero más eficientes para operaciones numéricas.


## Creación de Arreglos <a id='creacion-arreglos'></a>

In [7]:

# Crear un arreglo 1D
arr1 = np.array([1, 2, 3, 4, 5])
print("Arreglo 1D:", arr1)

# Crear un arreglo 2D
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Arreglo 2D:\n", arr2)

# Crear arreglos con ceros y unos
ceros_arr = np.zeros((2, 3))
unos_arr = np.ones((3, 3))

print("Arreglo de ceros:\n", ceros_arr)
print("Arreglo de unos:\n", unos_arr)

# Crear un arreglo con un rango de valores
# numpy.arange([start, ]stop[, step, ], dtype=None)
# start (opcional): Es el valor inicial del rango. Si no se proporciona, el valor predeterminado es 0.
# stop: Es el valor final del rango (no incluido en el arreglo).
# step (opcional): Es el incremento entre cada número en el rango. El valor predeterminado es 1.
# dtype (opcional): Especifica el tipo de dato de los elementos en el arreglo resultante. Si no se proporciona, NumPy intentará inferir el tipo automáticamente.

rango_arr = np.arange(3, 11, 1)
print("Arreglo con rango:", rango_arr)


Arreglo 1D: [1 2 3 4 5]
Arreglo 2D:
 [[1 2 3]
 [4 5 6]]
Arreglo de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Arreglo de unos:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arreglo con rango: [ 3  4  5  6  7  8  9 10]


## Operaciones con Arreglos <a id='operaciones-arreglos'></a>

In [8]:

# Operaciones básicas con arreglos
arr = np.array([10, 20, 30, 40])

# Suma
resultado_suma = arr + 5
print("Después de sumar 5:", resultado_suma)

# Multiplicación
resultado_mult = arr * 2
print("Después de multiplicar por 2:", resultado_mult)

# Operaciones entre dos arreglos (elemento por elemento)
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
suma_arreglos = arr_a + arr_b
producto_arreglos = arr_a * arr_b

print("Suma de arreglos:", suma_arreglos)
print("Producto de arreglos:", producto_arreglos)


Después de sumar 5: [15 25 35 45]
Después de multiplicar por 2: [20 40 60 80]
Suma de arreglos: [5 7 9]
Producto de arreglos: [ 4 10 18]


## Indexación y Slicing <a id='indexacion-slicing'></a>

In [9]:

# Indexación y slicing en arreglos NumPy
arr = np.array([10, 20, 30, 40, 50])

# Acceso a elementos
print("Primer elemento:", arr[0])
print("Último elemento:", arr[-1])

# Slicing
corte_arr = arr[1:4]
print("Arreglo cortado (1:4):", corte_arr)

# Modificar elementos
arr[0] = 100
print("Arreglo modificado:", arr)


Primer elemento: 10
Último elemento: 50
Arreglo cortado (1:4): [20 30 40]
Arreglo modificado: [100  20  30  40  50]


## Funciones Matemáticas <a id='funciones-matematicas'></a>

In [2]:

# Usando funciones matemáticas en NumPy
arr = np.array([1, 2, 3, 4, 5])

# Raíz cuadrada
sqrt_arr = np.sqrt(arr)
print("Raíz cuadrada del arreglo:", sqrt_arr)

# Exponencial
exp_arr = np.exp(arr)
print("Exponencial del arreglo:", exp_arr)

# Media y desviación estándar
media = np.mean(arr)
desv_std = np.std(arr)

print("Media:", media)
print("Desviación estándar:", desv_std)


Raíz cuadrada del arreglo: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponencial del arreglo: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Media: 3.0
Desviación estándar: 1.4142135623730951


## Broadcasting <a id='broadcasting'></a>

In [6]:

# Broadcasting permite que NumPy realice operaciones con arreglos de diferentes formas
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
print("Arreglo 1:\n", arr1,"\n")
print("Arreglo 2:\n", arr2,"\n")
# Suma con broadcasting
resultado_broadcasting = arr1 + arr2
print("Resultado de Broadcasting:\n", resultado_broadcasting)


Arreglo 1:
 [1 2 3] 

Arreglo 2:
 [[1]
 [2]
 [3]] 

Resultado de Broadcasting:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


## Cambio de Forma en Arreglos <a id='cambio-forma'></a>

In [8]:

# Cambiando la forma de un arreglo
arr = np.arange(1, 10)
arr_reshaped = arr.reshape(3, 3)
print("Arreglo con nueva forma (3x3):\n", arr_reshaped)

# Aplanar el arreglo
arr_aplanado = arr_reshaped.flatten()
print("Arreglo aplanado:\n", arr_aplanado)


Arreglo con nueva forma (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Arreglo aplanado:
 [1 2 3 4 5 6 7 8 9]
